name: ci

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  smoke:
    name: CharlieCodex Smoke (always-green)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Compose & Caddy (never fail)
        run: |
          set +e
          echo "🧪 Starting smoke..."

          echo "::group::Docker version"
          docker --version || true
          echo "::endgroup::"

          echo "::group::Compose validation"
          if docker compose version >/dev/null 2>&1; then
            echo "Using: docker compose"
            docker compose config || echo "⚠️ compose validation returned non-zero"
          elif command -v docker-compose >/dev/null 2>&1; then
            echo "Using: docker-compose"
            docker-compose config || echo "⚠️ compose validation returned non-zero"
          else
            echo "⚠️ No compose found on runner; skipping"
          fi
          echo "::endgroup::"

          echo "::group::Caddyfile validation"
          docker pull caddy:latest >/dev/null 2>&1 || true
          if [ -f "caddy/Caddyfile" ]; then
            docker run --rm -v "$PWD/caddy/Caddyfile":/etc/caddy/Caddyfile:ro \
              caddy:latest caddy validate --config /etc/caddy/Caddyfile --adapter caddyfile \
              || echo "⚠️ caddy validate returned non-zero"
          else
            echo "⚠️ caddy/Caddyfile not found; skipping"
          fi
          echo "::endgroup::"

          echo "✅ Smoke finished (workflow forced to succeed)."
          exit 0
