name: CI – Validate Compose & Caddy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show versions
        run: |
          docker --version
          docker compose version

      - name: Validate docker-compose.yml (syntax & render)
        run: |
          docker compose -f docker-compose.yml config >/dev/null

      - name: Validate Caddyfile with official image
        run: |
          docker run --rm -v "$PWD/caddy:/caddy:ro" caddy:latest \
            caddy validate --config /caddy/Caddyfile --adapter caddyfile

      - name: Ensure .gitignore blocks runtime/data (no tracked files)
        run: |
          set -e
          BLOCKED_PATHS=$(git ls-files | grep -E '^(postgres/|redis/|meili/|meili_data/|minio/|caddy/(data|config)/|\.env($|\.))' || true)
          if [ -n "$BLOCKED_PATHS" ]; then
            echo "::error::Há arquivos de runtime/segredo versionados:"
            echo "$BLOCKED_PATHS"
            exit 1
          fi

      - name: Quick secret scan (basic)
        run: |
          set -e
          ! (grep -RInE '(MINIO_ROOT_PASSWORD|MEILI_MASTER_KEY|POSTGRES_PASSWORD)=' . \
              --exclude-dir=.git --exclude-dir=.github --exclude=*.md || true | grep -v ".env.example")
