name: ci

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  smoke:
    name: CharlieCodex Smoke Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Docker Compose syntax
        run: docker compose config > /dev/null

      - name: Validate Caddyfile syntax
        run: |
          docker run --rm \
            -v "$PWD/caddy/Caddyfile":/etc/caddy/Caddyfile:ro \
            caddy:latest caddy validate --config /etc/caddy/Caddyfile --adapter caddyfile

      - name: Print success confirmation
        run: echo "✅ CharlieCodex CI pipeline passed successfully!"
